language: node_js
node_js:
  - "0.10"
  - "0.8"

services:
  - mongodb
  - postgresql
  - riak
  - mysql

before_script:
  - psql -c 'create database model_test;' -U postgres
  - sudo apt-get install mysql-server mysql-client
  - mysql -u root -e "CREATE DATABASE model_test COLLATE latin1_general_cs;"
  - sudo apt-get install sqlite3 libsqlite3-dev

script: jake test --trace
